### ISSUE TITLE
OSM sync feature displays nodes in incorrect order

### ISSUE THREAD

**Issue by jaa2** [jmather625/OSM_buildingdetector#11]
![osm_map_1](https://user-images.githubusercontent.com/43010335/50668822-3a063e00-0f87-11e9-8117-e22380c9a7f1.PNG)

When a building looking like this appears on OSM, the sync feature shows a building with its nodes in the wrong order:

![osm_map_2_in_osmbd](https://user-images.githubusercontent.com/43010335/50668836-50ac9500-0f87-11e9-9609-96c521c437c2.PNG)

Here is another example.

Building on OSM:
![osm_map_ex2](https://user-images.githubusercontent.com/43010335/50668898-9c5f3e80-0f87-11e9-8b9a-eef792d2cd1f.PNG)

In OSM Building Detector:
![osm_map_ex2_2](https://user-images.githubusercontent.com/43010335/50668902-a41ee300-0f87-11e9-8026-2394e071eb73.PNG)

**Comment by jmather625** [comment]
I think this was solved in the latest push onto the branch improveAlgorithm

**Comment by jaa2** [comment]
It's still broken. Scroll just northeast of the testing location to see these results. It also seems that the display is inconsistent. Sometimes, the same buildings that become the bowtie X shape become rectangles again after changing the view location or the zoom.
